{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9fe09684-9b16-4693-88d3-8db9610fee70",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os, random\n",
    "from datetime import date\n",
    "from PIL import Image\n",
    "import streamlit as st\n",
    "\n",
    "# ----------------------------\n",
    "# Settings you should customize\n",
    "# ----------------------------\n",
    "LOVER_NAME = \"Lily\"   # <-- change\n",
    "YOUR_NAME = \"Yuanyuan\"  # <-- change\n",
    "BIRTHDAY = date(2026, 3, 5)  # <-- change (YYYY, M, D)\n",
    "\n",
    "TITLE = f\"Happy Birthday, {LOVER_NAME}! 🎂\"\n",
    "OPENING = (\n",
    "    \"Today is all about you.\\n\\n\"\n",
    "    \"Thank you for being my favourite person, my safe place, and my best surprise.\"\n",
    ")\n",
    "\n",
    "LOVE_NOTES = [\n",
    "    \"I love the way you laugh — it instantly makes my day better.\",\n",
    "    \"With you, even ordinary days feel special.\",\n",
    "    \"You make me feel understood, supported, and loved.\",\n",
    "    \"I’m proud of you — always.\",\n",
    "]\n",
    "\n",
    "PROMISES = [\n",
    "    \"More hugs. More photos. More sunsets together.\",\n",
    "    \"More patience, more listening, more growing together.\",\n",
    "    \"More dates, more adventures, more tiny everyday happiness.\",\n",
    "]\n",
    "\n",
    "# Folder of photos\n",
    "PHOTO_DIR = \"photos\"\n",
    "\n",
    "\n",
    "# ----------------------------\n",
    "# App UI\n",
    "# ----------------------------\n",
    "st.set_page_config(page_title=TITLE, page_icon=\"🎉\", layout=\"wide\")\n",
    "\n",
    "st.title(TITLE)\n",
    "st.caption(f\"Made with ❤️ by {YOUR_NAME}\")\n",
    "\n",
    "# Countdown / status\n",
    "today = date.today()\n",
    "days = (BIRTHDAY - today).days\n",
    "if days > 0:\n",
    "    st.info(f\"🎈 {days} days until your birthday!\")\n",
    "elif days == 0:\n",
    "    st.success(\"🎉 It's your birthday today!!!\")\n",
    "else:\n",
    "    st.warning(f\"🎀 Happy belated birthday! (It was {-days} days ago)\")\n",
    "\n",
    "st.write(OPENING)\n",
    "\n",
    "st.divider()\n",
    "\n",
    "# Photo gallery\n",
    "st.subheader(\"Our Memories 📸\")\n",
    "\n",
    "photo_paths = []\n",
    "if os.path.isdir(PHOTO_DIR):\n",
    "    for fn in os.listdir(PHOTO_DIR):\n",
    "        if fn.lower().endswith((\".jpg\", \".jpeg\", \".png\", \".webp\")):\n",
    "            photo_paths.append(os.path.join(PHOTO_DIR, fn))\n",
    "\n",
    "photo_paths.sort()\n",
    "\n",
    "if not photo_paths:\n",
    "    st.warning(\"No photos found. Please put images into the 'photos/' folder.\")\n",
    "else:\n",
    "    # Slider to pick photo\n",
    "    idx = st.slider(\"Pick a photo\", 1, len(photo_paths), 1) - 1\n",
    "    img = Image.open(photo_paths[idx])\n",
    "    st.image(img, use_container_width=True)\n",
    "\n",
    "    # Optional: show thumbnails in columns\n",
    "    with st.expander(\"Show all photos\"):\n",
    "        cols = st.columns(3)\n",
    "        for i, p in enumerate(photo_paths):\n",
    "            with cols[i % 3]:\n",
    "                st.image(Image.open(p), use_container_width=True, caption=os.path.basename(p))\n",
    "\n",
    "st.divider()\n",
    "\n",
    "# Love notes section\n",
    "st.subheader(\"A few things I love about you 💌\")\n",
    "st.write(\"Click for a random note:\")\n",
    "\n",
    "if \"note\" not in st.session_state:\n",
    "    st.session_state.note = random.choice(LOVE_NOTES)\n",
    "\n",
    "if st.button(\"Give me a love note\"):\n",
    "    st.session_state.note = random.choice(LOVE_NOTES)\n",
    "\n",
    "st.success(st.session_state.note)\n",
    "\n",
    "st.divider()\n",
    "\n",
    "# Promises / wishes\n",
    "st.subheader(\"My wish for you 🌟\")\n",
    "st.write(\"May you be happy, healthy, and surrounded by love — today and always.\")\n",
    "st.write(\"And here’s my promise:\")\n",
    "\n",
    "if \"promise\" not in st.session_state:\n",
    "    st.session_state.promise = random.choice(PROMISES)\n",
    "\n",
    "if st.button(\"Show my promise\"):\n",
    "    st.session_state.promise = random.choice(PROMISES)\n",
    "\n",
    "st.info(st.session_state.promise)\n",
    "\n",
    "st.divider()\n",
    "\n",
    "# Hidden \"easter egg\"\n",
    "st.subheader(\"One last thing… 🫶\")\n",
    "with st.expander(\"Open when you miss me\"):\n",
    "    st.write(\n",
    "        f\"Hey {LOVER_NAME},\\n\\n\"\n",
    "        \"If you’re reading this, I want you to know:\\n\"\n",
    "        \"I’m always on your side.\\n\\n\"\n",
    "        \"Come here — you deserve a big hug. 🤍\"\n",
    "    )\n",
    "\n",
    "st.caption(\"Tip: You can deploy this as a link later (Streamlit Community Cloud).\")\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python (coms762tutorial)",
   "language": "python",
   "name": "coms762tutorial"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
